package com.emiliano.fmframework.optimization.csa.constraintPropagator;

public class ConstraintPropagators {
	public static ClauseBasedConstraintPropagator clauseBasedConstraintPropagator=new ClauseBasedConstraintPropagator();
	public static CardinalityBasedConstraintPropagator cardinalityBasedConstraintPropagator=new CardinalityBasedConstraintPropagator();
}
